//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFC-ZahlenHai.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCZAHLENHAI_DIALOG         102
#define ID_BUTTON_RULES                 103
#define IDS_RULES                       104
#define IDS_PLAYER_WINS                 105
#define IDS_VERSION_INFO                106
#define IDS_COMPUTER_WINS               107
#define IDS_DRAW                        108
#define IDS_MAX_POINTS                  109
#define IDS_MAX_POINTS_NEW              110
#define IDS_MAX_POINTS_INFORMATION      111
#define IDS_QUESTION                    112
#define IDS_WARNING                     113
#define IDS_INVALID_INPUT               114
#define IDS_ZUG                         115
#define IDS_SPIELER                     116
#define IDS_HAI                         117
#define IDS_SPIELER_PUNKTE              118
#define IDS_HAI_PUNKTE                  119
#define IDS_REST                        120
#define IDS_TOOLTIP_BUTTON              121
#define IDS_PLAYER_WINS_2               122
#define IDS_BUTTON_STARTNEW             123
#define IDS_BUTTON_END                  124
#define IDS_BUTTON_RULES                125
#define IDS_BUTTON_OK                   126
#define IDS_BUTTON_MAX_POINTS           127
#define IDS_BUTTON_OPTION               128
#define IDS_BUTTON_REST                 129
#define IDS_EDIT4                       130
#define IDS_MAX_POINTS_HEADLINE         131
#define IDS_DRAW_HEADLINE               132
#define IDS_COMPUTER_WINS_HEADLINE      133
#define IDS_PLAYER_WINS_HEADLINE        134
#define IDS_LOGFILE_DATE                135
#define IDS_LOGFILE_NAME                136
#define IDS_LOGFILE_POINTS_PLAYER       137
#define IDS_LOGFILE_POINTS_COMPUTER     138
#define IDS_LOGFILE_ROUNDS              139
#define IDS_VALID_INPUT_HEADLINE        140
#define IDS_RULES_HEADLINE              141
#define IDD_DIALOG1                     142
#define IDS_LOGFILE_HEADLINE            143
#define IDS_TOOL_TIP_TEXT               144
#define IDS_LOGFILE_MAXPOINTS           145
#define IDS_PLAYER_WINS2                146
#define IDS_GAME_IDEA                   147
#define IDS_TIME                        148
#define IDS_PRIME                       149
#define IDS_LOGFILE_LOCATION            150
#define IDS_TOOL_TIP_TEXT_NO_FACTORS    151
#define IDS_FILE_NAME                   152
#define IDS_PLAYER_WINS_OPTIMAL         153
#define IDA_PLAYER_WINS_OPTIMAL         154
#define IDS_SUM_TEXT                    155
#define IDS_LOGFILE_NUMBERS             156
#define IDS_RULES_2                     157
#define IDS_MAX_POINTS_INFORMATION2     158
#define IDS_DISCLAIMER_TEXT             159
#define IDS_MAX_POINTS_HEADLINE2        160
#define IDS_INFO_TEXT                   161
#define IDS_PRIME_INFO                  162
#define IDS_REG_TRUE                    163
#define IDS_SHARK_AGAINST               164
#define IDB_BITMAP1                     165
#define IDS_GAME_DATA                   166
#define IDB_BITMAP2                     167
#define IDS_HELP_FILE                   168
#define IDB_BITMAP3                     169
#define IDS_TITLE_VERSION               170
#define IDS_NUMBER_SHARK                171
#define IDS_OPTIONS_HEAD_TEXT           172
#define IDS_OPTIONS_HEAD                173
#define IDS_OPTIONS_TOOLTIPS            174
#define IDB_BITMAP6                     175
#define IDS_OPTIONS_SHOW_DIALOG         176
#define IDB_BITMAP7                     177
#define IDS_OPTIONS_SHOW_NUMBERS        178
#define IDS_OPTIONS_MAX_POINTS          179
#define IDS_STRING_PT                   180
#define IDS_MAX_POINTS_OLD              181
#define IDS_TOOL_TIP_NUMBER             182
#define IDB_BITMAP8                     183
#define IDS_TOOL_TIP_ISFACTOR           184
#define IDB_BITMAP4                     185
#define IDS_START_INFO                  186
#define IDD_GAME_RULES                  187
#define IDS_LOG_LEAD                    188
#define IDB_BITMAP5                     189
#define IDS_LOG_BEHIND                  190
#define IDS_SPRACHE                     191
#define IDS_LED_WIN                     192
#define IDD_GAME_SUMMARY                193
#define IDS_LED_LOST                    194
#define IDD_MFCZAHLENHAI_DIALOG1        195
#define IDD_SEARCH_PROGRESS             196
#define IDS_LED_DRAW                    197
#define IDS_ZUG2                        198
#define IDS_SPIELER2                    199
#define IDS_HAI2                        200
#define IDS_SPIELER_PUNKTE2             201
#define IDS_HAI_PUNKTE2                 202
#define IDS_REST2                       203
#define IDS_ISNOT_FACTOR                204
#define IDS_ISNOT_FACOTR                205
#define IDR_ACCELERATOR1                206
#define IDS_RADIO_EDIT1                 207
#define IDS_RADIO_EDIT2                 208
#define IDS_TAB_HEADER1                 209
#define IDD_DIALOG2                     210
#define IDS_TAB_HEADER2                 211
#define IDD_DIALOG3                     212
#define IDS_TAB_HEADER3                 213
#define IDS_TAB_RADIO1                  214
#define IDB_BITMAP_UNDO                 215
#define IDS_SEARCH2                     216
#define IDB_BITMAP_REDO                 217
#define IDS_BUTTON_HELP                 218
#define IDS_WARNING_SHORT               219
#define IDS_MAX_POINTS_INFORMATION_NOVALUE 220
#define IDS_TOOL_TIP_UNDO               221
#define IDS_TOOL_TIP_REDO               222
#define IDR_MAINFRAME1                  223
#define IDS_MAX_POINTS_NEW_2            224
#define IDB_BITMAP9                     225
#define IDS_SHELL_GROUB_BOX             226
#define IDS_SHELL_GROUP_BOX             227
#define IDB_BITMAP10                    228
#define IDS_NORMAL_GROUP_BOX            229
#define IDS_NO_SEARCH                   230
#define IDS_NO_SUMMARY                  231
#define IDS_IDS_VALID_INPUT_HEADLINE_LOW 232
#define IDS_VALID_INPUT_HEADLINE_LOW    233
#define IDS_LOGFILE_PLAYER_NUMBERS      234
#define IDR_MAINFRAME                   235
#define IDS_SEPERATOR                   236
#define IDS_TAB_HEADER4                 237
#define IDS_ACC_CHANGE                  238
#define IDS_ACC_LOAD                    239
#define IDS_ACC_SAVE                    240
#define IDS_PLAYER_WINS_OPTIMAL2        241
#define IDS_PLAYER_WINS3                242
#define IDS_NUMBER_ONE                  243
#define IDS_LOAD_FAILED                 244
#define IDS_ASK_FOR_USER_CANCELLATION   245
#define IDS_SELECT_SEARCH_ALGORITHM     246
#define IDS_GAME_DATA_FILE_MISSING      247
#define IDD_SHOW_PRECALCULATED_SCORES   248
#define IDS_BACKTRACKING_ALGORITHM_RESULT 249
#define IDD_SHOW_PRECALCULATED_SCORES_IN_DETAIL 250
#define IDS_SEARCH_PROGRESS_TEXT_1      251
#define IDS_SEARCH_PROGRESS_TEXT_2      252
#define IDS_ALGORITHM_BRUTE_FORCE       253
#define IDS_ALGORITHM_BACK_TRACKING     254
#define IDS_HEADING_NUMBER              255
#define IDS_HEADING_SCORE               256
#define IDS_HEADING_PROVED              257
#define IDS_PROVED_YES                  258
#define IDS_PROVED_NO                   259
#define IDS_SHOW_SEQUENCE_FOR_THIS_SPECIFIC_SCORE 260
#define IDS_PRECALCULATED_SCORES_INTRO  261
#define IDS_NO_SCORE_SELECTED           262
#define IDS_HEADING_SEQUENCE_LENGTH     263
#define IDS_HEADING_SEQUENCE            264
#define IDB_BITMAP_NUMBERSHARK_01       265
#define IDS_ACC_TAB                     266
#define IDB_BITMAP_NUMBERSHARK_02       267
#define IDS_ACC_ENTER_OR_SPACE          268
#define IDB_BITMAP_NUMBERSHARK_03       269
#define IDB_BITMAP_NUMBERSHARK_04       270
#define IDB_BITMAP_NUMBERSHARK_05       271
#define IDB_BITMAP_NUMBERSHARK_06       272
#define IDB_BITMAP_NUMBERSHARK_07       273
#define IDB_BITMAP_NUMBERSHARK_08       274
#define IDB_BITMAP_NUMBERSHARK_09       275
#define IDS_TOOLTIP_BUTTON_LOADGAME     276
#define IDS_TOOLTIP_BUTTON_SAVEGAME     277
#define IDS_TAB_RADIO2                  278
#define IDS_SEARCH1                     279
#define IDS_TOOLTIP_BUTTON_SWITCH_STYLE 280
#define IDC_LIST2                       1001
#define IDC_EDIT1                       1007
#define IDC_BUTTON1                     1008
#define IDC_BUTTON_OK                   1008
#define IDC_BUTTON_MAX                  1008
#define IDC_EDIT2                       1014
#define IDC_EDIT_NAME                   1014
#define IDC_EDIT3                       1036
#define IDC_BUTTON01                    1046
#define IDC_BUTTON02                    1047
#define IDC_BUTTON03                    1048
#define IDC_BUTTON04                    1049
#define IDC_BUTTON05                    1050
#define IDC_BUTTON06                    1051
#define IDC_BUTTON07                    1052
#define IDC_BUTTON08                    1053
#define IDC_BUTTON09                    1054
#define IDC_BUTTON10                    1055
#define IDC_BUTTON11                    1056
#define IDC_BUTTON12                    1057
#define IDC_BUTTON13                    1058
#define IDC_BUTTON14                    1059
#define IDC_BUTTON15                    1060
#define IDC_BUTTON16                    1061
#define IDC_BUTTON17                    1062
#define IDC_BUTTON18                    1063
#define IDC_BUTTON19                    1064
#define IDC_BUTTON20                    1065
#define IDC_BUTTON21                    1066
#define IDC_BUTTON22                    1067
#define IDC_BUTTON23                    1068
#define IDC_BUTTON24                    1069
#define IDC_BUTTON25                    1070
#define IDC_BUTTON26                    1071
#define IDC_BUTTON27                    1072
#define IDC_BUTTON28                    1073
#define IDC_BUTTON29                    1074
#define IDC_BUTTON30                    1075
#define IDC_BUTTON_STARTNEW             1078
#define ID_BUTTON_END                   1079
#define IDC_BUTTON2                     1080
#define IDC_BUTTON_MAX_POINTS           1080
#define IDC_BUTTON_HELP                 1080
#define IDC_TAB1                        1091
#define IDC_EDIT4                       1092
#define IDC_BUTTON3                     1093
#define IDC_BUTTON_OPTION               1093
#define IDC_BUTTON_REST                 1094
#define IDC_CHECK1                      1101
#define IDC_BUTTON4                     1102
#define IDC_BUTTON_UNDO                 1102
#define IDC_STATIC_LISTE                1103
#define IDC_STATIC_BLOCK                1104
#define IDC_STATIC_EINSTELLUNGEN        1105
#define IDC_STATIC_SUM                  1106
#define IDC_STATIC_MAIL                 1107
#define IDC_STATIC_MAIL2                1108
#define IDC_STATIC_MAIL3                1109
#define IDC_STATIC_INFO                 1109
#define IDC_CHECK2                      1111
#define IDC_STATIC_DISCLAIMER           1112
#define IDC_STATIC_IDEA                 1113
#define IDC_CHECK3                      1114
#define IDC_STATIC_MAX_POINTS_TEXT      1116
#define IDC_STATIC_MAX_POINTS_GROUP     1117
#define IDC_STATIC_HAI_LISTE            1119
#define IDC_LEDTEXT                     1120
#define IDC_LED_WINNER                  1122
#define IDC_RICHEDIT21                  1127
#define IDC_START_INFO                  1128
#define IDC_OPTION_START                1132
#define IDC_OPTION_TOOLTIP              1133
#define IDC_OPTION_GAME_START           1134
#define IDC_OPTION_REMEMBER             1135
#define IDC_RICHEDIT_SUMMARY            1136
#define IDC_RADIO1                      1137
#define IDC_RADIO2                      1138
#define IDC_RADIO_MAX1                  1139
#define IDC_RADIO_MAX2                  1140
#define IDC_STATIC4                     1146
#define IDC_STATIC1                     1147
#define IDC_STATIC2                     1148
#define IDC_STATIC3                     1149
#define IDC_STATIC5                     1150
#define IDC_STATIC_MAXVALUE             1151
#define IDC_BUTTON_FINISH               1152
#define IDC_BUTTON_REDO                 1154
#define IDC_GAME_IDEA                   1156
#define IDC_DISCLAIMER_TEXT             1157
#define IDC_INFO_TEXT                   1158
#define IDC_BUTTON_SWITCH_STYLE         1167
#define IDC_TIMER                       1168
#define IDC_BUTTON_LOAD                 1170
#define IDC_BUTTON_SAVE                 1171
#define IDC_ACCELERATORS                1174
#define IDC_TEXT_SEARCH_PROGRESS_1      1175
#define IDC_TEXT_SEARCH_PROGRESS_2      1176
#define IDC_STATIC_INTRO                1178
#define IDC_EDIT_PRECALCULATED_SCORES   1179
#define ID_SHOW_DETAILS                 1180
#define IDC_LIST_PRECALCULATED_SCORES   2069
#define ID_OPTIONEN_TOOLTIPSANZEIGEN    32771
#define ID_OPTIONEN_MAXIMALPUNKTEZAHL   32772
#define ID_OPTIONEN_MITHAIBEGINNEN      32773
#define ID_DATEI_NEUESSPIEL             32774
#define ID_DATEI_SPIELSPEICHERN         32775
#define ID_DATEI_SPIELSPEICHERNUNTER    32776
#define ID_DATEI_ENDE                   32777
#define ID_GIVE_REST                    32780
#define ID_OPEN_RULES                   32786
#define ID_ACCELERATOR_CHANGESTYLE      32788
#define ID_ACCELERATOR_LOADGAME         32790
#define ID_ACCELERATOR_SAVEGAME         32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           175
#endif
#endif
