// Automatically generated file while compilation. Do NOT edit this file manually. 		
 
// Commands (ID_* and IDM_*) 								
#define HID_BUTTON_RULES                        0x10003
#define HIDM_ABOUTBOX                           0x10010
#define HID_BUTTON_END                          0x10437
#define HID_OPTIONEN_TOOLTIPSANZEIGEN           0x18003
#define HID_OPTIONEN_MAXIMALPUNKTEZAHL          0x18004
#define HID_OPTIONEN_MITHAIBEGINNEN             0x18005
#define HID_DATEI_NEUESSPIEL                    0x18006
#define HID_DATEI_SPIELSPEICHERN                0x18007
#define HID_DATEI_SPIELSPEICHERNUNTER           0x18008
#define HID_DATEI_ENDE                          0x18009
#define HID_GIVE_REST                           0x1800C
#define HID_OPEN_RULES                          0x18012
 
// Prompts (IDP_*) 									
 
// Ressources (IDR_*) 								
#define HIDR_ACCELERATOR1                       0x200B7
#define HIDR_MAINFRAME1                         0x200C5
#define HIDR_MAINFRAME                          0x200CD
 
// Dialogs (IDD_*) 									
#define HIDD_ABOUTBOX                           0x20064
#define HIDD_MFCZAHLENHAI_DIALOG                0x20066
#define HIDD_DIALOG1                            0x2008A
#define HIDD_GAME_RULES                         0x200AB
#define HIDD_GAME_SUMMARY                       0x200AE
#define HIDD_MFCZAHLENHAI_DIALOG1               0x200AF
#define HIDD_DIALOG2                            0x200BA
#define HIDD_DIALOG3                            0x200BB
 
// Frame Controls (IDW_*) 									
