#define SECUDE_VERSION_MAJ 7
#define SECUDE_VERSION_MIN 4
#define SECUDE_VERSION_BUG 60
#define SECUDE_VERSION_STATE "C"
#define SECUDE_VERSION_STAGE sec_ver_release
#define SECUDE_VERSION_YEAR "2006"
#define SECUDE_VERSION_Y 2006
#define SECUDE_VERSION_LIB  70460

