#if !defined(AFX_TRAPEZEDITOR_H__19F2A6A3_7F43_4B91_A2A1_DA4C40248D91__INCLUDED_)
#define AFX_TRAPEZEDITOR_H__19F2A6A3_7F43_4B91_A2A1_DA4C40248D91__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTrapezEditor wrapper class

class CTrapezEditor : public CWnd
{
protected:
	DECLARE_DYNCREATE(CTrapezEditor)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x90393a34, 0x2f31, 0x48a4, { 0x93, 0x23, 0x8c, 0xec, 0x42, 0xc7, 0x39, 0x54 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetDisplayColorTable();
	void SetDisplayColorTable(BOOL);
	LPUNKNOWN GetColortable();
	void SetColortable(LPUNKNOWN);
	long GetResolution();
	void SetResolution(long);
	float GetHistScale();
	void SetHistScale(float);
	LPUNKNOWN GetHistogram();
	void SetHistogram(LPUNKNOWN);
	short GetDrawstyle();
	void SetDrawstyle(short);
	BOOL GetDisplayHistogram();
	void SetDisplayHistogram(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TRAPEZEDITOR_H__19F2A6A3_7F43_4B91_A2A1_DA4C40248D91__INCLUDED_)
